env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
  sourceType: 'module'
rules:
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn
  no-var:
    - error
  eqeqeq:
    - error