env:
  browser: true
  commonjs: true
  es2021: true
extends: 'eslint:recommended'
parser: '@typescript-eslint/parser'
plugins:
  - "@typescript-eslint"
parserOptions:
  ecmaVersion: 12
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
    -
      SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - warn